### ISSUE TITLE
Add example Sass Source file

### ISSUE THREAD

**Issue by denniserdmann** [ErdmannFreunde/contao-grid-bundle#1]
see https://github.com/ErdmannFreunde/euf_grid/issues/21

**Comment by bezin** [comment]
As I dig into it, because I was sure I have seen that all somewhere before: Isn't that basically [_grid.scss](https://github.com/ErdmannFreunde/euf_nutshell/blob/develop/files/nutshell/scss/base/_grid.scss) from your Nutshell framework and the mixins?

**Comment by denniserdmann** [comment]
it is, but not separated from the framework.
