### ISSUE TITLE
Probleme nach Update auf Version 1.1.0

### ISSUE THREAD

**Issue by contaoacademy** [ErdmannFreunde/contao-grid-bundle#15]
Hallo @denniserdmann,

nach dem Update von `1.0.8` auf `1.1.0` habe ich Probleme mit dem Layout bei zahlreichen Installationen.
So ganz genau kann ich die Ursache noch nicht ausmachen.
Es sieht so aus, also ob die CSS-Definitionen fehlen würde.

Als schnelle Übergangslösung habe ich jetzt ein Downgrade auf die `1.0.8` gemacht bzw. einen Conflict für die Version 1.1.0 eingetragen.

**Comment by denniserdmann** [comment]
Danke für den Hinweis. Das Problem sollte nun mit 1.1.1 behoben sein: https://github.com/erdmannfreunde/contao-grid-bundle/commit/58f095a60875e1e17d46a5029ecd2df0ea2177ed

**Comment by contaoacademy** [comment]
Danke. Sieht gut aus.
