### ISSUE TITLE
Reihe Start Fehler bei Update auf neuste Version 1.1.0

### ISSUE THREAD

**Issue by Eaglemong** [ErdmannFreunde/contao-grid-bundle#16]
Nach dem Update eurer Version 1.1.0 funktioniert mein Contentelement "Reihe Start" nicht mehr ordnungsgemäß. Der übernimmt nicht meine Klassen darin und außerdem lädt er irgendwie auch nicht eure CSS. Bei mir steht alles jetzt untereinander.

**Comment by denniserdmann** [comment]
siehe #15 

Klappt es mit 1.1.1?

**Comment by Eaglemong** [comment]
Hi Dennis,

nein ich habe die Version 1.1.1. Habe mich oben verschrieben. Sorry.

**Comment by denniserdmann** [comment]
Dann kannst du wie von Christian beschrieben auf die Version 1.0.8 zurückwechseln bis das Problem behoben ist.

**Comment by Eaglemong** [comment]
Ja hab mir gerade den Commit angeschaut. Danke dafür! :)
