### ISSUE TITLE
EuF-Grid CSS wird nicht geladen

### ISSUE THREAD

**Issue by michaelgawlik** [ErdmannFreunde/contao-grid-bundle#17]
Hallo Freunde,
die EuF-Grid CSS Datei wird nach dem letzten Update (1.0.8 -> 1.1.1). nicht mehr geladen.
Beim zurücksetzen auf die 1.0.8 funktioniert alles wieder.

PHP: 8.1
Contao 4.13

**Comment by richardhj** [comment]
Das ist in Version 1.1.2 gefixt. 4a8f547144e61cbcd89250ee7b1b88f7080afd44

**Comment by michaelgawlik** [comment]
Kann ich so bestätigen. Vielen Dank.
