### ISSUE TITLE
GRID wird nicht übernommen

### ISSUE THREAD

**Issue by samazaphikel** [ErdmannFreunde/contao-grid-bundle#24]
Hallo,
ich habe mir gestern das Bundle installiert.

Ich habe 2 Textfelder, die nebeneinander sollen. Nur leider bleibt das untereinander.

jetzt habe ich bemerkt, dass wenn ich einen längeren Text habe das Grid nicht funktioniert. Wenn der Text kurz genug ist ohne Zeilenumbruch, dann steht es nebeneinander. Wenn der Text länger ist, dann stehen die Texte untereinander.

Gibt es dazu ein Lösungvorschlag?

**Comment by denniserdmann** [comment]
Moin!

Wir sprechen von einem Formular, richtig? Hast du die Textfelder mit einem Reihe-Start- und Ende umschlossen? Du kannst dir auch mal bei uns auf der Website die Doku ansehen: https://erdmann-freunde.de/dokumentationen/contao-erweiterungen/euf-grid

Was für Inhaltselemente gilt, gilt auch für Formularfelder. 

_Nachtrag: Wenn du die notwendigen CSS-Anweisungen für das Grid nicht selbst schreiben möchtest, musst du im Seitenlayout noch einen Haken setzen, um das EuF-Grid zu laden._

**Comment by samazaphikel** [comment]
Nein, kein Formular. Nur die Startseite.

Und ist mit Start Ende Reihe.
CSS ist in der Theme Einstellung aktiviert

Sobald ich zuhause bin, schaue ich mir das auf der Seite genauer an und melde mich dann nochmal

**Comment by samazaphikel** [comment]
So, ich habe es jetzt nochmal getestet. Wie gesagt, der Haken unter Themes **EuF-Grid CSS laden** ist aktiviert.

Im Artikel wurde Start und Ende Reihe eingefügt:
![Bildschirmfoto vom 2024-01-24 16-20-43](https://github.com/erdmannfreunde/contao-grid-bundle/assets/35742942/8cc08edb-bd17-4d81-9547-f7dbe389518c)


Und im frontend ist es dann untereinander:
![Bildschirmfoto vom 2024-01-24 16-21-11](https://github.com/erdmannfreunde/contao-grid-bundle/assets/35742942/dd20e28f-cd2d-4efe-92ee-f3ef5d80a3cf)



in der Frontend HTML Ansicht sieht das so aus:
```
<main id="main">
<div class="inside">
<div class="mod_article block" id="article-273">
<div class="row ce_rowStart">
<div class="word-wrap: break-word; col-4 ">
<div class="content-text">
<h1>Aktuelles</h1>
<div class="rte">
<p style="text-align: left;">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
</div>
</div>
</div><div class="col-4 ">
<div class="content-text">
<h1>Letzter</h1>
<div class="rte">
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</main>
```
ebenso ist das css geladen worden.

Und dann das ganze mit gekürztem Text:
![Bildschirmfoto vom 2024-01-24 16-22-45](https://github.com/erdmannfreunde/contao-grid-bundle/assets/35742942/e63752ad-9155-4976-aa46-7a05dbfafc8c)
Dann  im frontend mit kurzem Text:

![Bildschirmfoto vom 2024-01-24 16-23-08](https://github.com/erdmannfreunde/contao-grid-bundle/assets/35742942/e096b9fd-0652-4f4b-92b5-3af898d8c3ea)

**Comment by denniserdmann** [comment]
Das ist sehr merkwürdig. Wir haben die Installationen in so gut wie allen Projekten im Einsatz, auch unter Contao 5. Es gibt nur einen Unterschied: wir nutzen nicht die CSS-Datei, die der Erweiterung beiliegt, sondern das Grid aus dem Nutshell Framework. Es könnte also sein, dass eine Anweisung für Grid-Klassen ohne Viewport fehlt. In dem Fall müsste es aber funktionieren, wenn du stattdessen die Grid-Klasse col-md-6 verwendest. 

Falls das nicht hilft:  Kannst du mir einen Link zu per mail senden? Dann schaue ich selbst mal drauf.

**Comment by samazaphikel** [comment]
Hi,

ich habe gerade den Fehler gefunden.

Es gibt einen Konflikt mit der CSS aus dem Theme.

```
.container .row,.sectionTop .inside .row,.sectionTop .inside .mod_newslist,.sectionTop .inside .mod_eventlist,.sectionTop .inside .mod_newsarchive,.sectionTop .inside .left-col #container,.left-col .sectionTop .inside #container,.sectionTop .inside .right-col #container,.right-col .sectionTop .inside #container,.sectionTop .inside .left-right-col #container,.left-right-col .sectionTop .inside #container,#header .nav-wrapper .row,#header .nav-wrapper .mod_newslist,#header .nav-wrapper .mod_eventlist,#header .nav-wrapper .mod_newsarchive,#header .nav-wrapper .left-col #container,.left-col #header .nav-wrapper #container,#header .nav-wrapper .right-col #container,.right-col #header .nav-wrapper #container,#header .nav-wrapper .left-right-col #container,.left-right-col #header .nav-wrapper #container,.container .mod_newslist,.container .mod_eventlist,.container .mod_newsarchive,.container .left-col #container,.left-col .container #container,.container .right-col #container,.right-col .container #container,.container .left-right-col #container,.left-right-col .container #container {
    margin-left: -.75rem;
    margin-right: -.75rem;
    display: -webkit-flex;
    display: -ms-flex;
    display: flex;
    //-webkit-flex-wrap: wrap;
    //-ms-flex-wrap: wrap;
    //flex-wrap: wrap;
    clear: left
}
```
Die auskommentierten Zeilen habe ich versucht über die custom.css  zu überschreiben und ändert sich auch nicht  wenn (auch wenn man es nicht machen sollte) im vendor Ordner direkt geändert wird,

Trotz dessen, dass ich im Backend unter Systemwartung den Cache gelöscht habe, sowie auch den sämtlichen Cache im Contao-Manager. Die zeilen bleiben bestehen....

**Comment by denniserdmann** [comment]
In Systemwartung die Assets löschen, dann sollte auf jeden Fall ein Unterschied zu sehen sein, sofern sie nicht noch an anderer Stelle erneut gesetzt werden. 

Genau genommen sind alle Anweisungen, die du oben genannt hast, nicht gut, denn das Theme verwendet flexbox und die Grid-Erweiterung `display: grid` (da braucht man auch keinen negativen margin).

Ich denke, du musst dich für eine Lösung entscheiden.

**Comment by samazaphikel** [comment]
Ja, leider werden die CSS Änderungen nicht übernommen. Habe wie gesagt in der Systemwartung alles Jobs aktiviert.

Habe alle flexbox Elemente bereits aus dem Vendor Theme Ordner entfernt und dennoch stehen die da drin…

Ich werde mich morgen nochmal länger hinsetzen und nochmal jede CSS überprüfen
