### ISSUE TITLE
An Mitgliedergruppen heften 

### ISSUE THREAD

**Issue by katgirl** [ErdmannFreunde/contao-grid-bundle#25]
Es wäre schön, wenn man die Reihe und auch die Spalten künftig an Mitgliedergruppen hängen kann.

```{protected_legend:hide},protected;```

Hintergrund ist, das wir diese als Umschlagselement verwenden, z.B. für die Klasse ```card``` und dann leere Boxen haben.

**Comment by denniserdmann** [comment]
Ich verstehe den Anwendungsfall bisher nicht. Vielleicht kannst du es nochmal konkretisieren.

**Comment by katgirl** [comment]
![image](https://github.com/erdmannfreunde/contao-grid-bundle/assets/1223243/a6b5a53b-fb54-4e83-86ce-ae92878f2ba4)

An der Spalte ist die CSS-Klasse ```card```welche einen Rahmen setzt. Wenn die Inhalte innen drin geschützt sind, entsteht eine leere Box. 
Man kann es einfach umgehen, in dem man ein anderes Element nimmt bei dem man es schützt und dann zurück auf Spalte stellt. Schön wäre es wenn man das direkt machen kann. 
Man müsste nur im DCA die Parameter hinzu tun ;-)
https://github.com/erdmannfreunde/contao-grid-bundle/blob/2.x/contao/dca/tl_content.php#L13-L17

Schön wäre, wenn es das auch für die 1.X gibt.

**Comment by denniserdmann** [comment]
Ich habe die Änderungen für die 1.X ergänzt.

Für die Version 2 bzw. Contao 5 werden wir langfristig die Reihe-Start-Ende und Spalte-Start-Ende durch die Verschachtelten Elemente ersetzen. Es ist jetzt bereits möglich, das Gruppen-Element für Spalten zu nutzen und dort lassen sich die Inhalte auch auf Mitglieder-Gruppen beschränken.

**Wichtig für 1.X:** Wenn man ein Start-Element schützt, muss auch das Ende-Element schützen, andernfalls hat man einen schließenden Container zu viel.

**Comment by katgirl** [comment]
Danke
